<a href="https://colab.research.google.com/github/hrshtmlng/NLP/blob/main/Fake_NewsClassifierUsingLSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Fake News Classifier Using LSTM

Dataset: https://www.kaggle.com/c/fake-news/data#

In [ ]:
import pandas as pd

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("algord/fake-news")

print("Path to dataset files:", path)

100%|██████████| 1.68M/1.68M [00:00<00:00, 121MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/algord/fake-news/versions/1


In [ ]:
df=pd.read_csv(f'{path}/FakeNewsNet.csv')

In [ ]:
df.head()

title  \
0  Kandi Burruss Explodes Over Rape Accusation on...   
1  People's Choice Awards 2018: The best red carp...   
2  Sophia Bush Sends Sweet Birthday Message to 'O...   
3  Colombian singer Maluma sparks rumours of inap...   
4  Gossip Girl 10 Years Later: How Upper East Sid...   

                                            news_url        source_domain  \
0  http://toofab.com/2017/05/08/real-housewives-a...           toofab.com   
1  https://www.today.com/style/see-people-s-choic...        www.today.com   
2  https://www.etonline.com/news/220806_sophia_bu...     www.etonline.com   
3  https://www.dailymail.co.uk/news/article-33655...  www.dailymail.co.uk   
4  https://www.zerchoo.com/entertainment/gossip-g...      www.zerchoo.com   

   tweet_num  real  
0         42     1  
1          0     1  
2         63     1  
3         20     1  
4         38     1

In [ ]:
df.shape

(23196, 5)

In [ ]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [ ]:
df.isnull().sum()

title              0
news_url         330
source_domain    330
tweet_num          0
real               0
dtype: int64

In [ ]:
###Drop Nan Values
df=df.dropna()


In [ ]:
df.head()

title  \
0  Kandi Burruss Explodes Over Rape Accusation on...   
1  People's Choice Awards 2018: The best red carp...   
2  Sophia Bush Sends Sweet Birthday Message to 'O...   
3  Colombian singer Maluma sparks rumours of inap...   
4  Gossip Girl 10 Years Later: How Upper East Sid...   

                                            news_url        source_domain  \
0  http://toofab.com/2017/05/08/real-housewives-a...           toofab.com   
1  https://www.today.com/style/see-people-s-choic...        www.today.com   
2  https://www.etonline.com/news/220806_sophia_bu...     www.etonline.com   
3  https://www.dailymail.co.uk/news/article-33655...  www.dailymail.co.uk   
4  https://www.zerchoo.com/entertainment/gossip-g...      www.zerchoo.com   

   tweet_num  real  
0         42     1  
1          0     1  
2         63     1  
3         20     1  
4         38     1

In [ ]:
X=df.drop('real',axis=1)

In [ ]:
y=df['real']

In [ ]:
X.shape

(22866, 4)

In [ ]:
y.shape

(22866,)

In [ ]:
import tensorflow as tf

In [ ]:
tf.__version__

'2.18.0'

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [ ]:
### Vocabulary size
voc_size=5000

### Onehot Representation

In [ ]:
messages=X.copy()

In [ ]:
messages['title'][1]

"People's Choice Awards 2018: The best red carpet looks"

In [ ]:
messages

title  \
0      Kandi Burruss Explodes Over Rape Accusation on...   
1      People's Choice Awards 2018: The best red carp...   
2      Sophia Bush Sends Sweet Birthday Message to 'O...   
3      Colombian singer Maluma sparks rumours of inap...   
4      Gossip Girl 10 Years Later: How Upper East Sid...   
...                                                  ...   
23191  Pippa Middleton wedding: In case you missed it...   
23192  Zayn Malik & Gigi Hadid’s Shocking Split: Why ...   
23193  Jessica Chastain Recalls the Moment Her Mother...   
23194  Tristan Thompson Feels "Dumped" After Khloé Ka...   
23195  Kelly Clarkson Performs a Medley of Kendrick L...   

                                                news_url  \
0      http://toofab.com/2017/05/08/real-housewives-a...   
1      https://www.today.com/style/see-people-s-choic...   
2      https://www.etonline.com/news/220806_sophia_bu...   
3      https://www.dailymail.co.uk/news/article-33655...   
4      https://www.zerchoo.com/entertainment/gossip-g...   
...                                                  ...   
23191  https://www.express.co.uk/news/royal/807049/pi...   
23192  hollywoodlife.com/2018/03/13/zayn-malik-gigi-h...   
23193  http://www.justjared.com/2018/01/17/jessica-ch...   
23194  www.intouchweekly.com/posts/tristan-thompson-f...   
23195  https://www.billboard.com/articles/news/bbma/8...   

               source_domain  tweet_num  
0                 toofab.com         42  
1              www.today.com          0  
2           www.etonline.com         63  
3        www.dailymail.co.uk         20  
4            www.zerchoo.com         38  
...                      ...        ...  
23191      www.express.co.uk         52  
23192      hollywoodlife.com          7  
23193      www.justjared.com         26  
23194  www.intouchweekly.com         24  
23195      www.billboard.com         85  

[22866 rows x 4 columns]

In [ ]:
messages.reset_index(inplace=True)

In [ ]:
messages

index                                              title  \
0          0  Kandi Burruss Explodes Over Rape Accusation on...   
1          1  People's Choice Awards 2018: The best red carp...   
2          2  Sophia Bush Sends Sweet Birthday Message to 'O...   
3          3  Colombian singer Maluma sparks rumours of inap...   
4          4  Gossip Girl 10 Years Later: How Upper East Sid...   
...      ...                                                ...   
22861  23191  Pippa Middleton wedding: In case you missed it...   
22862  23192  Zayn Malik & Gigi Hadid’s Shocking Split: Why ...   
22863  23193  Jessica Chastain Recalls the Moment Her Mother...   
22864  23194  Tristan Thompson Feels "Dumped" After Khloé Ka...   
22865  23195  Kelly Clarkson Performs a Medley of Kendrick L...   

                                                news_url  \
0      http://toofab.com/2017/05/08/real-housewives-a...   
1      https://www.today.com/style/see-people-s-choic...   
2      https://www.etonline.com/news/220806_sophia_bu...   
3      https://www.dailymail.co.uk/news/article-33655...   
4      https://www.zerchoo.com/entertainment/gossip-g...   
...                                                  ...   
22861  https://www.express.co.uk/news/royal/807049/pi...   
22862  hollywoodlife.com/2018/03/13/zayn-malik-gigi-h...   
22863  http://www.justjared.com/2018/01/17/jessica-ch...   
22864  www.intouchweekly.com/posts/tristan-thompson-f...   
22865  https://www.billboard.com/articles/news/bbma/8...   

               source_domain  tweet_num  
0                 toofab.com         42  
1              www.today.com          0  
2           www.etonline.com         63  
3        www.dailymail.co.uk         20  
4            www.zerchoo.com         38  
...                      ...        ...  
22861      www.express.co.uk         52  
22862      hollywoodlife.com          7  
22863      www.justjared.com         26  
22864  www.intouchweekly.com         24  
22865      www.billboard.com         85  

[22866 rows x 5 columns]

In [ ]:
import nltk
import re
from nltk.corpus import stopwords

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer ##stemming purpose
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()

    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [ ]:
corpus

['kandi burruss explod rape accus real housew atlanta reunion video',
 'peopl choic award best red carpet look',
 'sophia bush send sweet birthday messag one tree hill co star hilari burton breyton eva',
 'colombian singer maluma spark rumour inappropri relationship aunt',
 'gossip girl year later upper east sider shock world chang pop cultur forev',
 'gwen stefani got dump blake shelton jealousi drama exclus',
 'broward counti sheriff fire lie parkland',
 'amber rose shut french montana date rumor call rapper bruvaaa',
 'mindi kale make first post babi appear disneyland wrinkl time co star',
 'katharin mcphee butcher toni nomin drink',
 'wag miami star ashley nicol robert philip wheeler marri',
 'mel gibson hollywood pedophil nowher left hide',
 'medium tyler henri address chill messag kristin cavallari deceas brother express read',
 'dwt season result week disney night',
 'reason tarek el moussa overcom latest back injuri',
 'david cassidi cut estrang daughter kati complet leav son b

In [ ]:
corpus[1]

'peopl choic award best red carpet look'

In [ ]:
onehot_repr=[one_hot(words,voc_size)for words in corpus]
onehot_repr

[[3492, 741, 2362, 2651, 1384, 360, 2840, 1794, 1299, 2745],
 [2855, 791, 3962, 3812, 1141, 1420, 4406],
 [4888,
  1496,
  3687,
  3590,
  514,
  1014,
  626,
  157,
  4526,
  1438,
  1858,
  3671,
  4854,
  1326,
  716],
 [2499, 3236, 585, 3077, 4146, 2353, 1248, 789],
 [2176, 432, 3030, 393, 1042, 713, 2374, 1498, 4543, 218, 455, 764, 4906],
 [3721, 372, 1013, 1348, 2340, 224, 4202, 2622, 2917],
 [2822, 2278, 2486, 915, 2573, 2341],
 [1495, 2656, 4996, 1412, 973, 4921, 1542, 177, 4905, 4290],
 [3784, 450, 2343, 2261, 2428, 1381, 2611, 952, 2592, 3724, 1438, 1858],
 [4136, 4945, 4385, 3681, 4581, 3062],
 [4061, 2964, 1858, 2060, 3098, 474, 4967, 834, 2286],
 [4877, 1986, 1266, 4923, 4818, 2967, 4844],
 [2889, 1592, 2301, 549, 2708, 1014, 1948, 4595, 452, 3925, 800, 1057],
 [4784, 1449, 3078, 88, 4266, 4157],
 [2971, 1404, 3106, 4001, 4349, 2646, 2719, 1993],
 [4510, 2821, 2640, 4149, 4597, 3537, 3366, 1591, 1411, 4011],
 [4640, 4755, 779, 4966, 3507, 2885, 4886],
 [3304, 1273, 716, 20

In [ ]:
corpus[1]

'peopl choic award best red carpet look'

In [ ]:
onehot_repr[1]

[2855, 791, 3962, 3812, 1141, 1420, 4406]

### Embedding Representation

In [ ]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='post',maxlen=sent_length)
print(embedded_docs)

[[3492  741 2362 ...    0    0    0]
 [2855  791 3962 ...    0    0    0]
 [4888 1496 3687 ...    0    0    0]
 ...
 [3562 1721 4988 ...    0    0    0]
 [3965 4211 3334 ...    0    0    0]
 [1285  892 2357 ...    0    0    0]]


In [ ]:
embedded_docs[1]

array([2855,  791, 3962, 3812, 1141, 1420, 4406,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0], dtype=int32)

In [ ]:
embedded_docs[0]

array([3492,  741, 2362, 2651, 1384,  360, 2840, 1794, 1299, 2745,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0], dtype=int32)

In [ ]:
## Creating model
embedding_vector_features=40 ##features representation
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model.build(input_shape=(None, sent_length))
print(model.summary())

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (None, 20, 40)         │       200,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_2 (LSTM)                   │ (None, 100)            │        56,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 256,501 (1001.96 KB)

 Trainable params: 256,501 (1001.96 KB)

 Non-trainable params: 0 (0.00 B)

None


In [ ]:
len(embedded_docs),y.shape

(22866, (22866,))

In [ ]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [ ]:
X_final.shape,y_final.shape

((22866, 20), (22866,))

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

### Model Training

In [ ]:
### Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=15,batch_size=64)

Epoch 1/15
240/240 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.9424 - loss: 0.1402 - val_accuracy: 0.8089 - val_loss: 0.7333
Epoch 2/15
240/240 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.9482 - loss: 0.1219 - val_accuracy: 0.7938 - val_loss: 0.7391
Epoch 3/15
240/240 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.9501 - loss: 0.1159 - val_accuracy: 0.8003 - val_loss: 0.7330
Epoch 4/15
240/240 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.9569 - loss: 0.1055 - val_accuracy: 0.7959 - val_loss: 0.7513
Epoch 5/15
240/240 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.9643 - loss: 0.0908 - val_accuracy: 0.7905 - val_loss: 0.8166
Epoch 6/15
240/240 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.9699 - loss: 0.0808 - val_accuracy: 0.7869 - val_loss: 0.9567
Epoch 7/15
240/240 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.9707 - loss: 0.0807 - val_accuracy: 0.7872 - val_loss: 0.9260
Epoch 8/15
240/240 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.9742 - loss: 0.0673 - val_accuracy: 0.

### Adding Dropout

In [ ]:
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

### Performance Metrics And Accuracy

In [ ]:
y_pred=model.predict(X_test)

236/236 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step


In [ ]:
y_pred=np.where(y_pred > 0.6, 1,0) ##AUC ROC Curve

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
confusion_matrix(y_test,y_pred)

array([[1842,    0],
       [5704,    0]])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.24410283593957063

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.24      1.00      0.39      1842
           1       0.00      0.00      0.00      5704

    accuracy                           0.24      7546
   macro avg       0.12      0.50      0.20      7546
weighted avg       0.06      0.24      0.10      7546



/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [ ]:
import os
print(os.listdir(path))

['FakeNewsNet.csv']
